"""add tags to arts

Revision ID: 9bfc8eeaa5da
Revises: 529277b5c3e7
Create Date: 2024-07-07 14:15:28.749520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9bfc8eeaa5da'
down_revision: Union[str, None] = '529277b5c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('tags', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art', 'tags')
    # ### end Alembic commands ###
