"""initial db setup

Revision ID: 53ca3d368b9d
Revises: 
Create Date: 2024-04-14 11:55:10.167498

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53ca3d368b9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False, unique=True),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('language_code', sa.String(), nullable=True),
                    sa.Column('referrer', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.Column('external_id', sa.String(), nullable=True),
                    sa.Column('camunda_user_id', sa.String(), nullable=True),
                    sa.Column('camunda_key', sa.UUID(), nullable=False),
                    sa.Column('telegram_user_id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('webapp_user_id', sa.String(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
                    sa.Column('is_block', sa.Boolean(), nullable=False),
                    sa.Column('is_premium', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'camunda_key', 'telegram_user_id'),
                    sa.UniqueConstraint('telegram_user_id')
                    )
    op.create_table('arts',
                    sa.Column('id', sa.UUID(), nullable=False, unique=True),
                    sa.Column('art_name', sa.String(), nullable=False),
                    sa.Column('art_description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.Column('img_picture', sa.String(), nullable=True),
                    sa.Column('art_description_prompt', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('reference_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id', 'parent_id', 'user_id', 'reference_id')
                    )
    op.create_table('events',
                    sa.Column('id', sa.UUID(), nullable=False, unique=True),
                    sa.Column('event_name', sa.String(), nullable=False),
                    sa.Column('event_description', sa.String(), nullable=True),
                    sa.Column('img_event_cover', sa.String(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('reference_id', sa.UUID(), nullable=True),
                    sa.Column('art_ids', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id', 'reference_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('arts')
    op.drop_table('users')
    # ### end Alembic commands ###
