"""adding art and event fixes

Revision ID: 2da2b9a16a2f
Revises: e4b7e8c165c1
Create Date: 2024-03-30 09:13:40.777850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da2b9a16a2f'
down_revision: Union[str, None] = 'e4b7e8c165c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('art_name', sa.String(), nullable=False),
    sa.Column('art_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('img_art_thumbnail', sa.String(), nullable=True),
    sa.Column('art_description_prompt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('img_event_thumbnail', sa.String(), nullable=True),
    sa.Column('art_description_prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'external_id')
    op.drop_table('events')
    op.drop_table('arts')
    # ### end Alembic commands ###
